package Messaggistica;

import Dottore.HomeDottore;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bernardo
 */
public class DomandeDottore extends javax.swing.JFrame {

    private Chat chat;
    
    public DomandeDottore() {
        initComponents();
        chat = new Chat();
        chat.leggiMessaggi();
        visualizzaMessaggi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabellaDomande = new javax.swing.JTable();
        rispondiBtn = new javax.swing.JButton();
        estesaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Domande utenti");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tabellaDomande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Utente", "Categoria", "Domanda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabellaDomande.setRowHeight(30);
        tabellaDomande.setRowMargin(5);
        jScrollPane2.setViewportView(tabellaDomande);
        if (tabellaDomande.getColumnModel().getColumnCount() > 0) {
            tabellaDomande.getColumnModel().getColumn(0).setMinWidth(50);
            tabellaDomande.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabellaDomande.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 370));

        rispondiBtn.setText("Rispondi");
        rispondiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rispondiBtnMouseClicked(evt);
            }
        });
        background.add(rispondiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 140, -1));

        estesaBtn.setText("Visualizza domanda estesa");
        estesaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estesaBtnMouseClicked(evt);
            }
        });
        background.add(estesaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 190, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estesaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estesaBtnMouseClicked
        try {
            DefaultTableModel model = (DefaultTableModel) tabellaDomande.getModel();  
            String msg = "ID Domanda: " + model.getValueAt(tabellaDomande.getSelectedRow(), 0);
            msg += "\nUtente: " + model.getValueAt(tabellaDomande.getSelectedRow(), 1);
            msg += "\n\nCategoria: " + model.getValueAt(tabellaDomande.getSelectedRow(), 2);
            msg += "\n\nDomanda:\n" + model.getValueAt(tabellaDomande.getSelectedRow(), 3);
            JOptionPane.showMessageDialog(null, msg, "Domanda", JOptionPane.INFORMATION_MESSAGE);    
        } catch(ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Nessuna riga selezionata", "Domanda", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_estesaBtnMouseClicked

    private void rispondiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rispondiBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabellaDomande.getModel();
        String id = (String) model.getValueAt(tabellaDomande.getSelectedRow(), 0);
        String domanda = (String) model.getValueAt(tabellaDomande.getSelectedRow(), 3);
        FormRisposta fr = new FormRisposta(id, domanda);
        fr.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_rispondiBtnMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        HomeDottore hd = new HomeDottore();
        hd.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    public void visualizzaMessaggi() {
        ArrayList<String> domande = chat.getMessaggi();
        DefaultTableModel model = (DefaultTableModel) tabellaDomande.getModel();
        for(int i = 0; i < domande.size() / 4; i++) {
            model.addRow(new Object[] {
                domande.get(i*4),
                domande.get(i*4+1),
                domande.get(i*4+2),
                domande.get(i*4+3)
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DomandeDottore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DomandeDottore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DomandeDottore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DomandeDottore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DomandeDottore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton estesaBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rispondiBtn;
    private javax.swing.JTable tabellaDomande;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
