package Messaggistica;

import Messaggistica.Chat;
import javax.swing.JOptionPane;

/**
 *
 * @author Bernardo and Paolo
 */
public class DomandeUtente extends javax.swing.JFrame {

    Chat chat;
    /**
     * Creates new form ConsultaDottore
     */
    public DomandeUtente() {
        initComponents();
        chat = new Chat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrizione = new javax.swing.JTextArea();
        inviaBtn = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Consulta dottore");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Inserisci la descrizione della tua domanda (max 200 caratteri)");
        background.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 410, -1));

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non riesco a dimagrire", "Consiglio su cosa mangiare", "Suggerimento alimento mancante" }));
        background.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 410, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descrizione.setColumns(20);
        descrizione.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        descrizione.setLineWrap(true);
        descrizione.setRows(5);
        descrizione.setAutoscrolls(false);
        jScrollPane1.setViewportView(descrizione);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 410, 240));

        inviaBtn.setText("Invia domanda");
        inviaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inviaBtnMouseClicked(evt);
            }
        });
        background.add(inviaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 442, 410, 40));

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Seleziona la categoria della tua domanda");
        background.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inviaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inviaBtnMouseClicked
        String tipo_categoria = (String) categoria.getSelectedItem();
        String messaggio_descrizione = descrizione.getText();
        String msg = chat.inviaMessaggio(messaggio_descrizione, tipo_categoria);
        if(msg.equals("Messaggio inviato correttamente.")) {
            JOptionPane.showMessageDialog(null, msg, "Invio Messaggio", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, msg, "Invio Messaggio", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_inviaBtnMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Consulta consulta = new Consulta();
        consulta.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DomandeUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DomandeUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DomandeUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DomandeUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DomandeUtente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextArea descrizione;
    private javax.swing.JButton inviaBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
