package Messaggistica;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bernardo
 */
public class RisposteRicevute extends javax.swing.JFrame {

    private Chat chat;
    
    public RisposteRicevute() {
        initComponents();
        chat = new Chat();
        chat.visualizzaRisposte();
        setTabellaRisposte();
    }
    
    public void setTabellaRisposte() {
        ArrayList<String> risposte = chat.getRisposte();
        DefaultTableModel model = (DefaultTableModel) tabellaRisposte.getModel();
        for(int i = 0; i < risposte.size() / 4; i++) {
            model.addRow(new Object[] {
                risposte.get(i*4),
                risposte.get(i*4+1),
                risposte.get(i*4+2),
                risposte.get(i*4+3)
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellaRisposte = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 76, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Risposte ricevute");
        jPanel1.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        tabellaRisposte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Dottore", "Domanda", "Risposta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabellaRisposte.setRowHeight(30);
        tabellaRisposte.setRowMargin(5);
        jScrollPane1.setViewportView(tabellaRisposte);
        if (tabellaRisposte.getColumnModel().getColumnCount() > 0) {
            tabellaRisposte.getColumnModel().getColumn(0).setMinWidth(50);
            tabellaRisposte.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, 380));

        jButton1.setText("Visualizza risposta estesa");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 190, 40));

        jButton2.setText("Valuta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            DefaultTableModel model = (DefaultTableModel) tabellaRisposte.getModel();
            String msg = "ID Domanda: " + model.getValueAt(tabellaRisposte.getSelectedRow(), 0);
            msg += "\nDottore: " + model.getValueAt(tabellaRisposte.getSelectedRow(), 1);
            msg += "\n\nDomanda:\n" + model.getValueAt(tabellaRisposte.getSelectedRow(), 2);
            msg += "\n\nRisposta:\n" + model.getValueAt(tabellaRisposte.getSelectedRow(), 3);
            JOptionPane.showMessageDialog(null, msg, "Risposta", JOptionPane.INFORMATION_MESSAGE);
        } catch(ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Nessuna riga selezionata", "Risposta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultTableModel model = (DefaultTableModel) tabellaRisposte.getModel();
        String id = (String) model.getValueAt(tabellaRisposte.getSelectedRow(), 0);
        Valuta val = new Valuta(id);
        val.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Consulta cons = new Consulta();
        cons.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RisposteRicevute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RisposteRicevute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RisposteRicevute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RisposteRicevute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RisposteRicevute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabellaRisposte;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
