package Autenticazione;

import Admin.HomeAdmin;
import Dottore.HomeDottore;
import Impostazioni.JSON;
import Impostazioni.Richieste;
import Impostazioni.Xml_pars;
import java.util.Map;
import javax.swing.JOptionPane;
import Utente.Dashboard;
import java.io.IOException;
import java.io.InputStream;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.pdfbox.io.IOUtils;

/**
 *
 * @author Bernardo and Paolo
 */
public class Login extends javax.swing.JFrame {

    Richieste ric;
    Xml_pars xmlparser;
    JSON pj;
    String idlinkedin;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        xmlparser = new Xml_pars("Impostazioni.xml");

        if (!xmlparser.exists()) {
            xmlparser.ImpoDefault();
        }

        ric = new Richieste(xmlparser.getElement("PROTOCOL"), xmlparser.getElement("SERVER_ADDRES"), xmlparser.getElement("SERVER_PORTA"));
        pj = new JSON();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        nome_utente = new javax.swing.JLabel();
        campoNomeUtente = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        campoPassword = new javax.swing.JPasswordField();
        campoAccediCome = new javax.swing.JComboBox<>();
        accediCome = new javax.swing.JLabel();
        accediBtn = new javax.swing.JButton();
        registrazioneBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Login");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        nome_utente.setForeground(new java.awt.Color(255, 255, 255));
        nome_utente.setText("Nome utente");
        background.add(nome_utente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));
        background.add(campoNomeUtente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 310, 40));

        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        background.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        background.add(campoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, 40));

        campoAccediCome.setMaximumRowCount(3);
        campoAccediCome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Utente", "Dottore", "Admin" }));
        background.add(campoAccediCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 310, 40));

        accediCome.setForeground(new java.awt.Color(255, 255, 255));
        accediCome.setText("Accedi come");
        background.add(accediCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        accediBtn.setText("Accedi");
        accediBtn.setBorder(null);
        accediBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accediBtnMouseClicked(evt);
            }
        });
        background.add(accediBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 310, 40));

        registrazioneBtn.setText("Registrazione utenti");
        registrazioneBtn.setBorder(null);
        registrazioneBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrazioneBtnMouseClicked(evt);
            }
        });
        background.add(registrazioneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 150, 40));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrazioneBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrazioneBtnMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "La registrazione vale solo per gli utenti ordinari, non per dottori. Vuoi continuare?", "Registrazione", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            Registrazione reg = new Registrazione();
            reg.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_registrazioneBtnMouseClicked

    private void accediBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accediBtnMouseClicked
        String ruolo = (String) campoAccediCome.getSelectedItem();
        if (ruolo.equals("Utente")) {
            Utente utente = new Utente();
            String msg = utente.login(campoNomeUtente.getText(), campoPassword.getText());
            JOptionPane.showMessageDialog(null, msg, "Login", JOptionPane.INFORMATION_MESSAGE);
            if (msg.equals("Accesso effettuato correttamente.")) {
                Map dati = utente.prendiDatiUtente(campoNomeUtente.getText());
                dati.put("Tipologia", "utente");
                Xml_pars parser2 = new Xml_pars("token.save");
                parser2.ScriviXML("Utente", dati);
                Dashboard dash = new Dashboard();
                dash.setVisible(true);
                dispose();
            }
        } else if (ruolo.equals("Dottore")) {
            Dottore dott = new Dottore();
            String msg = dott.login(campoNomeUtente.getText(), campoPassword.getText());
            JOptionPane.showMessageDialog(null, msg, "Login", JOptionPane.INFORMATION_MESSAGE);
            if (msg.equals("Accesso effettuato correttamente.")) {
                Map dati = dott.prendiDatiDottore(campoNomeUtente.getText());
                dati.put("Tipologia", "dottore");
                Xml_pars parser2 = new Xml_pars("token.save");
                parser2.ScriviXML("Utente", dati);
                HomeDottore hd = new HomeDottore();
                hd.setVisible(true);
                dispose();
            }
        } else if (ruolo.equals("Admin")) {
            Admin admin = new Admin();
            String msg = admin.login(campoNomeUtente.getText(), campoPassword.getText());
            JOptionPane.showMessageDialog(null, msg, "Login", JOptionPane.INFORMATION_MESSAGE);
            if (msg.equals("Accesso effettuato correttamente.")) {
                HomeAdmin dash = new HomeAdmin();
                dash.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_accediBtnMouseClicked
    
    
    
    /*    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accediBtn;
    private javax.swing.JLabel accediCome;
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> campoAccediCome;
    private javax.swing.JTextField campoNomeUtente;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JLabel nome_utente;
    private javax.swing.JLabel password;
    private javax.swing.JButton registrazioneBtn;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables

}
