package Autenticazione;

import javax.swing.JOptionPane;

/**
 *
 * @author Bernardo and Paolo
 */
public class Registrazione extends javax.swing.JFrame {

    public Registrazione() {
        initComponents();
        campoEta.setValue(12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        nome_utente = new javax.swing.JLabel();
        campoNomeUtente = new javax.swing.JTextField();
        nome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        cognome = new javax.swing.JLabel();
        campoCognome = new javax.swing.JTextField();
        genere = new javax.swing.JLabel();
        campoGenere = new javax.swing.JComboBox<>();
        peso = new javax.swing.JLabel();
        campoPeso = new javax.swing.JSlider();
        kg = new javax.swing.JLabel();
        altezza = new javax.swing.JLabel();
        campoAltezza = new javax.swing.JSlider();
        cm = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        campoPassword = new javax.swing.JPasswordField();
        campoEta = new javax.swing.JSpinner();
        eta = new javax.swing.JLabel();
        registrazioneBtn = new javax.swing.JButton();
        accediBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Form di registrazione");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        nome_utente.setForeground(new java.awt.Color(255, 255, 255));
        nome_utente.setText("Nome utente");
        background.add(nome_utente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));
        background.add(campoNomeUtente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 310, 40));

        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setText("Nome");
        background.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));
        background.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 310, 40));

        cognome.setForeground(new java.awt.Color(255, 255, 255));
        cognome.setText("Cognome");
        background.add(cognome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));
        background.add(campoCognome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 310, 40));

        genere.setForeground(new java.awt.Color(255, 255, 255));
        genere.setText("Genere");
        background.add(genere, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        campoGenere.setMaximumRowCount(2);
        campoGenere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uomo", "Donna" }));
        background.add(campoGenere, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 310, 40));

        peso.setForeground(new java.awt.Color(255, 255, 255));
        peso.setText("Peso");
        background.add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        campoPeso.setMaximum(150);
        campoPeso.setValue(0);
        campoPeso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                campoPesoStateChanged(evt);
            }
        });
        background.add(campoPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 140, 20));

        kg.setForeground(new java.awt.Color(255, 255, 255));
        kg.setText("0 Kg");
        background.add(kg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        altezza.setForeground(new java.awt.Color(255, 255, 255));
        altezza.setText("Altezza");
        background.add(altezza, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        campoAltezza.setMaximum(210);
        campoAltezza.setValue(0);
        campoAltezza.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                campoAltezzaStateChanged(evt);
            }
        });
        background.add(campoAltezza, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 140, 20));

        cm.setForeground(new java.awt.Color(255, 255, 255));
        cm.setText("0 cm");
        background.add(cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        background.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));
        background.add(campoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 310, 40));

        campoEta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                campoEtaStateChanged(evt);
            }
        });
        background.add(campoEta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 130, -1));

        eta.setForeground(new java.awt.Color(255, 255, 255));
        eta.setText("Età");
        background.add(eta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        registrazioneBtn.setText("Registrati");
        registrazioneBtn.setBorder(null);
        registrazioneBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrazioneBtnMouseClicked(evt);
            }
        });
        background.add(registrazioneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 310, 40));

        accediBtn.setText("Accedi");
        accediBtn.setBorder(null);
        accediBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accediBtnMouseClicked(evt);
            }
        });
        background.add(accediBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 80, 40));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPesoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_campoPesoStateChanged
        kg.setText(campoPeso.getValue() + " kg");
    }//GEN-LAST:event_campoPesoStateChanged

    private void campoAltezzaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_campoAltezzaStateChanged
        cm.setText(campoAltezza.getValue() + "  cm");
    }//GEN-LAST:event_campoAltezzaStateChanged

    private void registrazioneBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrazioneBtnMouseClicked
        Utente utente = new Utente();
        String msg = utente.registrazione(campoNome.getText(),
                campoCognome.getText(),
                campoGenere.getSelectedItem().toString(),
                campoAltezza.getValue(),
                campoPeso.getValue(),
                campoNomeUtente.getText(),
                campoPassword.getText(), 
                (int) campoEta.getValue());
        
        if(msg.equals("registrazione riuscita")) {
            int n = JOptionPane.showConfirmDialog(null, "Confermi di volerti registrare al sistema?", "Conferma registrazione", JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION) {
                utente.nuovoUtente();
                JOptionPane.showMessageDialog(null, "Nuovo utente creato correttamente.", "Registrazione", JOptionPane.INFORMATION_MESSAGE);
                Login log = new Login();
                log.setVisible(true);
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, msg, "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrazioneBtnMouseClicked

    private void campoEtaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_campoEtaStateChanged
        int value = (int) campoEta.getValue();
        if(value == -1) {
            campoEta.setValue(0);
        }
    }//GEN-LAST:event_campoEtaStateChanged

    private void accediBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accediBtnMouseClicked
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_accediBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrazione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accediBtn;
    private javax.swing.JLabel altezza;
    private javax.swing.JPanel background;
    private javax.swing.JSlider campoAltezza;
    private javax.swing.JTextField campoCognome;
    private javax.swing.JSpinner campoEta;
    private javax.swing.JComboBox<String> campoGenere;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeUtente;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JSlider campoPeso;
    private javax.swing.JLabel cm;
    private javax.swing.JLabel cognome;
    private javax.swing.JLabel eta;
    private javax.swing.JLabel genere;
    private javax.swing.JLabel kg;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nome_utente;
    private javax.swing.JLabel password;
    private javax.swing.JLabel peso;
    private javax.swing.JButton registrazioneBtn;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
