package Utente;

import Impostazioni.Calendario;
import javax.swing.JOptionPane;

/**
 *
 * @author Bernardo and Paolo
 */
public class ResocontoUtente extends javax.swing.JFrame {

    Calendario calendario;
    ValutazioneResoconto vr;
    /**
     * Creates new form ResocontoUtente
     */
    public ResocontoUtente() {
        initComponents();
        calendario = new Calendario();
        vr = new ValutazioneResoconto();
        data.setText(calendario.getGiorno());
        String msg = vr.setProprietaMacronutrienti(calendario.getGiorno());
        if(msg.equals("Resoconto non disponibile per questa data.")) {
            JOptionPane.showMessageDialog(null, msg, "Resoconto non disponibile", JOptionPane.WARNING_MESSAGE);
            impostaProprieta(0); //SETTA TUTTI I VALORI NULL
        } else {
            msg = vr.setProprietaPasti(calendario.getGiorno(), "colazione");
            if(!msg.equals("Resoconto non disponibile per questa data.")) {
                msg = vr.setProprietaPasti(calendario.getGiorno(), "spuntino");
                if(!msg.equals("Resoconto non disponibile per questa data.")) {
                    msg = vr.setProprietaPasti(calendario.getGiorno(), "pranzo");
                    if(!msg.equals("Resoconto non disponibile per questa data.")) {
                        msg = vr.setProprietaPasti(calendario.getGiorno(), "cena");
                        if(!msg.equals("Resoconto non disponibile per questa data.")) {
                            nessun.setVisible(false);
                            impostaProprieta(1); //PRENDE TUTTI I VALORI DALL'OGGETTO VALUTAZIONE RESOCONTO
                        } else {
                            JOptionPane.showMessageDialog(null, "Resoconto non completo", "Resoconto non disponibile", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Resoconto non completo", "Resoconto non disponibile", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Resoconto non completo", "Resoconto non disponibile", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Resoconto non completo", "Resoconto non disponibile", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        data = new javax.swing.JLabel();
        avanti = new javax.swing.JLabel();
        indietro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cenaPanel = new javax.swing.JPanel();
        cenaLabel = new javax.swing.JLabel();
        caloriePanel = new javax.swing.JPanel();
        calorieLabel = new javax.swing.JLabel();
        carboidratiPanel = new javax.swing.JPanel();
        carboidratiLabel = new javax.swing.JLabel();
        proteinePanel = new javax.swing.JPanel();
        proteineLabel = new javax.swing.JLabel();
        grassiPanel = new javax.swing.JPanel();
        grassiLabel = new javax.swing.JLabel();
        colazionePanel = new javax.swing.JPanel();
        colazioneLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        spuntinoPanel = new javax.swing.JPanel();
        spuntinoLabel = new javax.swing.JLabel();
        pranzoPanel = new javax.swing.JPanel();
        pranzoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nessun = new javax.swing.JLabel();
        legenda = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Resoconto");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        dataPanel.setOpaque(false);

        data.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        data.setForeground(new java.awt.Color(255, 255, 255));
        data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        data.setText("Data");
        data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        avanti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avanti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_sort_right_30px.png"))); // NOI18N
        avanti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        avanti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avantiMouseClicked(evt);
            }
        });

        indietro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indietro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_sort_left_30px.png"))); // NOI18N
        indietro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        indietro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                indietroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanelLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(indietro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avanti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(avanti, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(indietro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        background.add(dataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 500, 50));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cenaLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cenaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cenaLabel.setText("Cena");

        javax.swing.GroupLayout cenaPanelLayout = new javax.swing.GroupLayout(cenaPanel);
        cenaPanel.setLayout(cenaPanelLayout);
        cenaPanelLayout.setHorizontalGroup(
            cenaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cenaPanelLayout.createSequentialGroup()
                .addComponent(cenaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cenaPanelLayout.setVerticalGroup(
            cenaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cenaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(cenaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 100, 50));

        calorieLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        calorieLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calorieLabel.setText("Calorie");

        javax.swing.GroupLayout caloriePanelLayout = new javax.swing.GroupLayout(caloriePanel);
        caloriePanel.setLayout(caloriePanelLayout);
        caloriePanelLayout.setHorizontalGroup(
            caloriePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calorieLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        caloriePanelLayout.setVerticalGroup(
            caloriePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calorieLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(caloriePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 460, 50));

        carboidratiLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        carboidratiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carboidratiLabel.setText("Carboidrati");

        javax.swing.GroupLayout carboidratiPanelLayout = new javax.swing.GroupLayout(carboidratiPanel);
        carboidratiPanel.setLayout(carboidratiPanelLayout);
        carboidratiPanelLayout.setHorizontalGroup(
            carboidratiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carboidratiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        carboidratiPanelLayout.setVerticalGroup(
            carboidratiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carboidratiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(carboidratiPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 460, 50));

        proteineLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        proteineLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proteineLabel.setText("Proteine");

        javax.swing.GroupLayout proteinePanelLayout = new javax.swing.GroupLayout(proteinePanel);
        proteinePanel.setLayout(proteinePanelLayout);
        proteinePanelLayout.setHorizontalGroup(
            proteinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(proteineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        proteinePanelLayout.setVerticalGroup(
            proteinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(proteineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(proteinePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 460, 50));

        grassiLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        grassiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grassiLabel.setText("Grassi");

        javax.swing.GroupLayout grassiPanelLayout = new javax.swing.GroupLayout(grassiPanel);
        grassiPanel.setLayout(grassiPanelLayout);
        grassiPanelLayout.setHorizontalGroup(
            grassiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grassiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        grassiPanelLayout.setVerticalGroup(
            grassiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grassiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(grassiPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 460, 50));

        colazioneLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        colazioneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colazioneLabel.setText("Colazione");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout colazionePanelLayout = new javax.swing.GroupLayout(colazionePanel);
        colazionePanel.setLayout(colazionePanelLayout);
        colazionePanelLayout.setHorizontalGroup(
            colazionePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colazionePanelLayout.createSequentialGroup()
                .addComponent(colazioneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        colazionePanelLayout.setVerticalGroup(
            colazionePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colazionePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(colazionePanelLayout.createSequentialGroup()
                .addComponent(colazioneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(colazionePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 50));

        spuntinoLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        spuntinoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spuntinoLabel.setText("Spuntino");

        javax.swing.GroupLayout spuntinoPanelLayout = new javax.swing.GroupLayout(spuntinoPanel);
        spuntinoPanel.setLayout(spuntinoPanelLayout);
        spuntinoPanelLayout.setHorizontalGroup(
            spuntinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spuntinoPanelLayout.createSequentialGroup()
                .addComponent(spuntinoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        spuntinoPanelLayout.setVerticalGroup(
            spuntinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spuntinoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(spuntinoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, 50));

        pranzoLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pranzoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pranzoLabel.setText("Pranzo");

        javax.swing.GroupLayout pranzoPanelLayout = new javax.swing.GroupLayout(pranzoPanel);
        pranzoPanel.setLayout(pranzoPanelLayout);
        pranzoPanelLayout.setHorizontalGroup(
            pranzoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pranzoPanelLayout.createSequentialGroup()
                .addComponent(pranzoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pranzoPanelLayout.setVerticalGroup(
            pranzoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pranzoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(pranzoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 100, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cena");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 100, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calorie");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 460, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Carboidrati");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 460, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Proteine");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 460, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Grassi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 460, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Colazione");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Spuntino");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 100, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pranzo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 100, 20));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 500, 400));

        nessun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nessun.setText("NESSUN RESOCONTO PER QUESTA DATA");
        background.add(nessun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 500, 430));

        legenda.setBackground(new java.awt.Color(255, 255, 255));
        legenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        legenda.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 10));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mangia ancora");
        legenda.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Perfetto");
        legenda.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 20));

        jPanel4.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        legenda.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 70, 10));

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        legenda.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 70, 10));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Troppo");
        legenda.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 90, 20));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Un pò troppo");
        legenda.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 90, 20));

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        legenda.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 70, 10));

        background.add(legenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 460, 40));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Legenda");
        background.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, 20));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avantiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avantiMouseClicked
        String cambioData = calendario.getGiornoSuccessivo();
        if(calendario.comparaDate()) {
            data.setText(cambioData);
            String msg = vr.setProprietaMacronutrienti(cambioData);
            if(msg.equals("Resoconto non disponibile per questa data.")) {
                JOptionPane.showMessageDialog(null, msg, "Resoconto non disponibile", JOptionPane.WARNING_MESSAGE);
                impostaProprieta(0); //SETTA TUTTI I VALORI NULL
                nessun.setVisible(true);
            } else {
                nessun.setVisible(false);
                vr.setProprietaPasti(cambioData, "colazione");
                vr.setProprietaPasti(cambioData, "spuntino");
                vr.setProprietaPasti(cambioData, "pranzo");
                vr.setProprietaPasti(cambioData, "cena");
                impostaProprieta(1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Non è possibile visualizzare il resoconto di giorni successivi ad oggi.", "Cambio data", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_avantiMouseClicked

    private void indietroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indietroMouseClicked
        String cambioData = calendario.getGiornoPrecedente();
        data.setText(cambioData);
        String msg = vr.setProprietaMacronutrienti(cambioData);
        if(msg.equals("Resoconto non disponibile per questa data.")) {
            JOptionPane.showMessageDialog(null, msg, "Resoconto non disponibile", JOptionPane.WARNING_MESSAGE);
            impostaProprieta(0); //SETTA TUTTI I VALORI NULL
            nessun.setVisible(true);
        } else {
            nessun.setVisible(false);
            vr.setProprietaPasti(cambioData, "colazione");
            vr.setProprietaPasti(cambioData, "spuntino");
            vr.setProprietaPasti(cambioData, "pranzo");
            vr.setProprietaPasti(cambioData, "cena");
            impostaProprieta(1);
        }
    }//GEN-LAST:event_indietroMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void impostaProprieta(int flag) {
        if(flag == 0) {
            jPanel1.setVisible(false);
        } else {
            jPanel1.setVisible(true);
            calorieLabel.setText("Hai assunto " + vr.getCalorieAssunte() + " di " + vr.getCalorieTotali() + "kcal");
            carboidratiLabel.setText("Hai assunto " + vr.getCarboidratiAssunti() + " di " + vr.getCarboidratiTotali() + "g");
            proteineLabel.setText("Hai assunto " + vr.getProteineAssunte() + " di " + vr.getProteineTotali() + "g");
            grassiLabel.setText("Hai assunto " + vr.getGrassiAssunti() + " di " + vr.getGrassiTotali() + "g");
            colazioneLabel.setText(vr.getColazioneAssunta() + "/" + vr.getColazioneTotale() + "kcal");
            spuntinoLabel.setText(vr.getSpuntinoAssunto() + "/" + vr.getSpuntinoTotale() + "kcal");
            pranzoLabel.setText(vr.getPranzoAssunto() + "/" + vr.getPranzoTotale() + "kcal");
            cenaLabel.setText(vr.getCenaAssunta() + "/" + vr.getCenaTotale() + "kcal");
            impostaStato();
        }
    }
    
    private void impostaStato() {
        caloriePanel.setBackground(vr.statoMacronutrienti(vr.getCalorieTotali(), vr.getCalorieAssunte()));
        carboidratiPanel.setBackground(vr.statoMacronutrienti(vr.getCarboidratiTotali(), vr.getCarboidratiAssunti()));
        proteinePanel.setBackground(vr.statoMacronutrienti(vr.getProteineTotali(), vr.getProteineAssunte()));
        grassiPanel.setBackground(vr.statoMacronutrienti(vr.getGrassiTotali(), vr.getGrassiAssunti()));
        colazionePanel.setBackground(vr.statoPasti(vr.getColazioneTotale(), vr.getColazioneAssunta()));
        spuntinoPanel.setBackground(vr.statoPasti(vr.getSpuntinoTotale(), vr.getSpuntinoAssunto()));
        pranzoPanel.setBackground(vr.statoPasti(vr.getPranzoTotale(), vr.getPranzoAssunto()));
        cenaPanel.setBackground(vr.statoPasti(vr.getCenaTotale(), vr.getCenaAssunta()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResocontoUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResocontoUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResocontoUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResocontoUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResocontoUtente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avanti;
    private javax.swing.JPanel background;
    private javax.swing.JLabel calorieLabel;
    private javax.swing.JPanel caloriePanel;
    private javax.swing.JLabel carboidratiLabel;
    private javax.swing.JPanel carboidratiPanel;
    private javax.swing.JLabel cenaLabel;
    private javax.swing.JPanel cenaPanel;
    private javax.swing.JLabel colazioneLabel;
    private javax.swing.JPanel colazionePanel;
    private javax.swing.JLabel data;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JLabel grassiLabel;
    private javax.swing.JPanel grassiPanel;
    private javax.swing.JLabel indietro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel legenda;
    private javax.swing.JLabel nessun;
    private javax.swing.JLabel pranzoLabel;
    private javax.swing.JPanel pranzoPanel;
    private javax.swing.JLabel proteineLabel;
    private javax.swing.JPanel proteinePanel;
    private javax.swing.JLabel spuntinoLabel;
    private javax.swing.JPanel spuntinoPanel;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
