package Informazioni;

import Dottore.HomeDottore;
import Impostazioni.Xml_pars;
import Utente.Dashboard;

/**
 *
 * @author Bernardo
 */
public class GestioneUtente extends javax.swing.JFrame {

    private UserManagement manage;
    private Xml_pars xmlparser;
    
    public GestioneUtente() {
        initComponents();
        manage = new UserManagement();
        manage.setInformazioni();
        nome_utente.setText(manage.getNomeUtente());
        nome.setText(manage.getNome());
        cognome.setText(manage.getCognome());
        eta.setText(manage.getEta());
        genere.setText(manage.getGenere());
        xmlparser = new Xml_pars("token.save");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cognome = new javax.swing.JLabel();
        nome_utente = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        eta = new javax.swing.JLabel();
        genere = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Gestione utente");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cognome");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 170, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Età");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nome utente");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Genere");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 170, -1));

        jButton1.setText("Cambio password");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 150, -1));

        cognome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cognome.setForeground(new java.awt.Color(255, 255, 255));
        cognome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cognome.setText("jLabel6");
        background.add(cognome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 130, 30));

        nome_utente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nome_utente.setForeground(new java.awt.Color(255, 255, 255));
        nome_utente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome_utente.setText("jLabel6");
        background.add(nome_utente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, 30));

        nome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome.setText("jLabel6");
        background.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 130, 30));

        eta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        eta.setForeground(new java.awt.Color(255, 255, 255));
        eta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eta.setText("jLabel6");
        background.add(eta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 130, 30));

        genere.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        genere.setForeground(new java.awt.Color(255, 255, 255));
        genere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genere.setText("jLabel6");
        background.add(genere, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 130, 30));

        jButton2.setText("Cambia età");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 150, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        CambioEta ce = new CambioEta();
        ce.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        String tipologia = xmlparser.getElement("Tipologia");
        if(tipologia.equals("utente")) {
            Dashboard dash = new Dashboard();
            dash.setVisible(true);
        } else if (tipologia.equals("dottore")) {
            HomeDottore hd = new HomeDottore();
            hd.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      CambioPassword cp = new CambioPassword();
        cp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestioneUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestioneUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestioneUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestioneUtente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestioneUtente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel cognome;
    private javax.swing.JLabel eta;
    private javax.swing.JLabel genere;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nome_utente;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
