package Alimentazione;

import Utente.Dashboard;
import javax.swing.JOptionPane;

/**
 *
 * @author Bernardo and Paolo
 */
public class Obiettivi1 extends javax.swing.JFrame {

    /**
     * Creates new form ImpostaObiettivo
     */
    public Obiettivi1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        comboObiettivo = new javax.swing.JComboBox<>();
        label1 = new javax.swing.JLabel();
        comboLavoro = new javax.swing.JComboBox<>();
        label2 = new javax.swing.JLabel();
        comboSport = new javax.swing.JComboBox<>();
        impostaObiettivoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Imposta obiettivo");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Seleziona l'obiettivo che vuoi raggiungere:");
        background.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, -1));

        comboObiettivo.setMaximumRowCount(4);
        comboObiettivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dimagrimento", "Mantenere il peso", "Sviluppo Muscolare" }));
        background.add(comboObiettivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 360, 40));

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Seleziona il livello di attività lavorativa:");
        background.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 500, -1));

        comboLavoro.setMaximumRowCount(4);
        comboLavoro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lavoro da scrivania", "Lavoro fisicamente attivo ma leggero", "Lavoro fisicamente pesante ma non eccessivamente", "Lavoro pesante" }));
        background.add(comboLavoro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 360, 40));

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Seleziona l'attività sportiva settimanale:");
        background.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 500, -1));

        comboSport.setMaximumRowCount(4);
        comboSport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non pratico sport", "almeno 2 volte" }));
        background.add(comboSport, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 360, 40));

        impostaObiettivoBtn.setText("Imposta obiettivo");
        impostaObiettivoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                impostaObiettivoBtnMouseClicked(evt);
            }
        });
        background.add(impostaObiettivoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 360, 40));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void impostaObiettivoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_impostaObiettivoBtnMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "Se già è stato impostato un obiettivo impostandone uno nuovo\nquello precedente verrà sovrascritto e verranno persi tutti gli alimenti assunti di oggi. Sei sicuro di voler procedere?", "Imposta obiettivo", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            String obiettivo = (String) comboObiettivo.getSelectedItem();
            String lavoro = (String) comboLavoro.getSelectedItem();
            String sport = (String) comboSport.getSelectedItem();
            Scheduler scheduler = new Scheduler();
            scheduler.setMetabolismoBasale();
            scheduler.setfabbisognoCalorico(lavoro, sport);
            scheduler.setMacronutrienti(obiettivo);
            scheduler.setPasti(obiettivo);
            String msg = scheduler.pianificazione();
            JOptionPane.showMessageDialog(null, msg, "Obiettivo", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_impostaObiettivoBtnMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Obiettivi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Obiettivi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Obiettivi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Obiettivi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Obiettivi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> comboLavoro;
    private javax.swing.JComboBox<String> comboObiettivo;
    private javax.swing.JComboBox<String> comboSport;
    private javax.swing.JButton impostaObiettivoBtn;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
