package Alimentazione;

import Alimentazione.Obiettivi2;
import Alimentazione.Alimento;
import javax.swing.JOptionPane;

/**
 *
 * @author Bernardo and Paolo
 */
public class RicercaAlimento extends javax.swing.JFrame {
    Alimento alim;
    /**
     * Creates new form RicercaAlimento
     */
    public RicercaAlimento() {
        initComponents();
        alim = new Alimento();
        resultPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        alimento = new javax.swing.JLabel();
        campoAlimento = new javax.swing.JTextField();
        cerca = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        labelRicerca = new javax.swing.JLabel();
        alimentiResult = new javax.swing.JComboBox<>();
        grammi = new javax.swing.JTextField();
        grammiLabel = new javax.swing.JLabel();
        inserisci = new javax.swing.JButton();
        comboPasto = new javax.swing.JComboBox<>();
        labelRicerca1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Assumi alimento");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        alimento.setForeground(new java.awt.Color(255, 255, 255));
        alimento.setText("Alimento");
        background.add(alimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));
        background.add(campoAlimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 40));

        cerca.setText("Cerca");
        cerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cercaMouseClicked(evt);
            }
        });
        background.add(cerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 90, 40));

        resultPanel.setOpaque(false);
        resultPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRicerca.setForeground(new java.awt.Color(255, 255, 255));
        labelRicerca.setText("Pasto");
        resultPanel.add(labelRicerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 360, -1));

        resultPanel.add(alimentiResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 460, 40));
        resultPanel.add(grammi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 80, 40));

        grammiLabel.setForeground(new java.awt.Color(255, 255, 255));
        grammiLabel.setText("Grammi");
        resultPanel.add(grammiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        inserisci.setText("Assumi");
        inserisci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inserisciMouseClicked(evt);
            }
        });
        resultPanel.add(inserisci, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, 40));

        comboPasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colazione", "Spuntino", "Pranzo", "Cena" }));
        resultPanel.add(comboPasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, 40));

        labelRicerca1.setForeground(new java.awt.Color(255, 255, 255));
        labelRicerca1.setText("Ricerca per: \"alimento\"");
        resultPanel.add(labelRicerca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        background.add(resultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 460, 190));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cercaMouseClicked
        String msg = "Alimenti trovati";
        msg = alim.getListaAlimenti(campoAlimento.getText());
        if(!msg.equals("Alimenti trovati")) {
            JOptionPane.showMessageDialog(null, "Nessun alimento trovato", "Ricerca", JOptionPane.INFORMATION_MESSAGE);
        } else {
            labelRicerca1.setText("Ricerca per: \'" + campoAlimento.getText() + "\'");
            resultPanel.setVisible(true);
            alimentiResult.removeAllItems();
            for(int i = 0; i < alim.lenElementi(); i++) {
                alimentiResult.addItem(alim.getAlimento(i));
            }
        }
    }//GEN-LAST:event_cercaMouseClicked

    private void inserisciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inserisciMouseClicked
        String elemento = (String) alimentiResult.getSelectedItem();
        String grammiInseriti = grammi.getText();
        String pasto = (String) comboPasto.getSelectedItem();
        String msg = alim.macronutrientiAlimento(elemento);
        if(msg.equals("Macronutrienti presi correttamente")) { 
            msg = alim.inserisciAlimentoAssunto(elemento, grammiInseriti, pasto);
            if(!msg.equals("Alimento non inserito")) {
                JOptionPane.showMessageDialog(null, msg, "Alimento assunto", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_inserisciMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       Obiettivi2 obt2 = new Obiettivi2();
       obt2.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RicercaAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RicercaAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RicercaAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RicercaAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RicercaAlimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alimentiResult;
    private javax.swing.JLabel alimento;
    private javax.swing.JPanel background;
    private javax.swing.JTextField campoAlimento;
    private javax.swing.JButton cerca;
    private javax.swing.JComboBox<String> comboPasto;
    private javax.swing.JTextField grammi;
    private javax.swing.JLabel grammiLabel;
    private javax.swing.JButton inserisci;
    private javax.swing.JLabel labelRicerca;
    private javax.swing.JLabel labelRicerca1;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
