package Admin;

import java.util.ArrayList;

/**
 *
 * @author Bernardo
 */
public class ControlloOperato extends javax.swing.JFrame {

    public Amministrazione amministrazione;
    
    public ControlloOperato() {
        initComponents();
        amministrazione = new Amministrazione();
        setComboDottori();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        operato = new javax.swing.JButton();
        comboDottori = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        domandeTotali = new javax.swing.JLabel();
        domandeConRisposta = new javax.swing.JLabel();
        domandeSenzaRisposta = new javax.swing.JLabel();
        risposteDottore = new javax.swing.JLabel();
        mediaValutazione = new javax.swing.JLabel();
        dt = new javax.swing.JLabel();
        dcr = new javax.swing.JLabel();
        dsr = new javax.swing.JLabel();
        rd = new javax.swing.JLabel();
        md = new javax.swing.JLabel();
        risultato = new javax.swing.JLabel();
        domandeTotali1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Controllo operato");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dottore");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 410, 20));

        operato.setText("Visualizza operato");
        operato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operatoMouseClicked(evt);
            }
        });
        background.add(operato, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 410, 40));

        background.add(comboDottori, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 410, 40));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 180));

        jPanel1.setBackground(new java.awt.Color(231, 76, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        domandeTotali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        domandeTotali.setForeground(new java.awt.Color(255, 255, 255));
        domandeTotali.setText("Informazioni relative al sistema");
        jPanel1.add(domandeTotali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        domandeConRisposta.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        domandeConRisposta.setForeground(new java.awt.Color(255, 255, 255));
        domandeConRisposta.setText("Domande con risposta");
        jPanel1.add(domandeConRisposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        domandeSenzaRisposta.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        domandeSenzaRisposta.setForeground(new java.awt.Color(255, 255, 255));
        domandeSenzaRisposta.setText("Domande senza risposta");
        jPanel1.add(domandeSenzaRisposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        risposteDottore.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        risposteDottore.setForeground(new java.awt.Color(255, 255, 255));
        risposteDottore.setText("Risposte dottore");
        jPanel1.add(risposteDottore, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 32));

        mediaValutazione.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        mediaValutazione.setForeground(new java.awt.Color(255, 255, 255));
        mediaValutazione.setText("Media valutazione");
        jPanel1.add(mediaValutazione, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, 32));

        dt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dt.setForeground(new java.awt.Color(255, 255, 255));
        dt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dt.setText("0");
        jPanel1.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 29, -1));

        dcr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dcr.setForeground(new java.awt.Color(255, 255, 255));
        dcr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dcr.setText("0");
        jPanel1.add(dcr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 29, -1));

        dsr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dsr.setForeground(new java.awt.Color(255, 255, 255));
        dsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dsr.setText("0");
        jPanel1.add(dsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 29, -1));

        rd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rd.setForeground(new java.awt.Color(255, 255, 255));
        rd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rd.setText("0");
        jPanel1.add(rd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 29, -1));

        md.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        md.setForeground(new java.awt.Color(255, 255, 255));
        md.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        md.setText("0");
        jPanel1.add(md, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 29, -1));

        risultato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        risultato.setForeground(new java.awt.Color(255, 255, 255));
        risultato.setText("Risultato dell'operato del dottore \"\"");
        jPanel1.add(risultato, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 409, 20));

        domandeTotali1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        domandeTotali1.setForeground(new java.awt.Color(255, 255, 255));
        domandeTotali1.setText("Domande Totali");
        jPanel1.add(domandeTotali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 500, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatoMouseClicked
        amministrazione.prendiDomandeRisposte((String) comboDottori.getSelectedItem());
        risultato.setText("Risultato dell'operato del dottore \"" + comboDottori.getSelectedItem() + "\"");
        dt.setText("" + amministrazione.getDomandeTotali());
        dcr.setText("" + amministrazione.getDomandeConRisposta());
        dsr.setText("" + amministrazione.getDomandeSenzaRisposta());
        rd.setText("" + amministrazione.getRisposteDottore());
        md.setText("" + amministrazione.getMediaValutazione());
    }//GEN-LAST:event_operatoMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        HomeAdmin ha = new HomeAdmin();
        ha.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    public void setComboDottori() {
        amministrazione.prendiDottori();
        ArrayList<String> dottore = amministrazione.getDottori();
        for(int i = 0; i < dottore.size(); i++) {
            comboDottori.addItem(dottore.get(i));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlloOperato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlloOperato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlloOperato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlloOperato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlloOperato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> comboDottori;
    private javax.swing.JLabel dcr;
    private javax.swing.JLabel domandeConRisposta;
    private javax.swing.JLabel domandeSenzaRisposta;
    private javax.swing.JLabel domandeTotali;
    private javax.swing.JLabel domandeTotali1;
    private javax.swing.JLabel dsr;
    private javax.swing.JLabel dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel md;
    private javax.swing.JLabel mediaValutazione;
    private javax.swing.JButton operato;
    private javax.swing.JLabel rd;
    private javax.swing.JLabel risposteDottore;
    private javax.swing.JLabel risultato;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
