package Admin;

import javax.swing.JOptionPane;

/**
 *
 * @author Bernardo
 */
public class GestionePiattaforma extends javax.swing.JFrame {

    private Amministrazione amministrazione;
    
    public GestionePiattaforma() {
        initComponents();
        amministrazione = new Amministrazione();
        campoEta.setValue(18);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoCognome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoNomeUtente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        campoEta = new javax.swing.JSpinner();
        campoGenere = new javax.swing.JComboBox<>();
        campoPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        campoElimina = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tipologia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(231, 76, 60));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titolo.setForeground(new java.awt.Color(255, 255, 255));
        titolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolo.setText("Gestione piattaforma");
        background.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, -1));
        jPanel1.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 180, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inserisci un nuovo dottore");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cognome");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));
        jPanel1.add(campoCognome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 180, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome_utente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, -1));
        jPanel1.add(campoNomeUtente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 120, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Genere");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 120, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Età");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 120, -1));

        jButton1.setText("Inserisci");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 410, 40));

        campoEta.setFocusable(false);
        campoEta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                campoEtaStateChanged(evt);
            }
        });
        jPanel1.add(campoEta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 180, 30));

        campoGenere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uomo", "Donna" }));
        jPanel1.add(campoGenere, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 180, 30));
        jPanel1.add(campoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 180, 30));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 270));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Elimina dottore/utente");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 20));

        jButton2.setText("Elimina");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 410, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 600, 10));
        jPanel2.add(campoElimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 260, 40));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome utente");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, 20));

        tipologia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dottore", "Utente" }));
        jPanel2.add(tipologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 130, 40));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 600, 180));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nome = campoNome.getText();
        String cognome = campoCognome.getText();
        String eta = "" + campoEta.getValue();
        String genere = (String) campoGenere.getSelectedItem();
        String password = campoPassword.getText();
        String nome_utente = campoNomeUtente.getText();
        String msg = amministrazione.inserisciDottore(nome, cognome, eta, genere, nome_utente, password);
        JOptionPane.showMessageDialog(null, msg, "Nuovo dottore", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void campoEtaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_campoEtaStateChanged
       int eta = (int) campoEta.getValue();
       if(eta < 18) {
           campoEta.setValue(18);
       }
    }//GEN-LAST:event_campoEtaStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String nome_utente = campoElimina.getText();
        String tipo = (String) tipologia.getSelectedItem();
        String msg = amministrazione.eliminaUtente(nome_utente, tipo);
        JOptionPane.showMessageDialog(null, msg, "Eliminazione", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        HomeAdmin ha = new HomeAdmin();
        ha.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionePiattaforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionePiattaforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionePiattaforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionePiattaforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionePiattaforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField campoCognome;
    private javax.swing.JTextField campoElimina;
    private javax.swing.JSpinner campoEta;
    private javax.swing.JComboBox<String> campoGenere;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeUtente;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> tipologia;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
